#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ViewsSample;
    
    #line 1 "..\..\Views\Home\Index.cshtml"
    using ViewsSample.Controllers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Hello Team</h2>\r\n<div>\r\n    My counter is: ");

            
            #line 9 "..\..\Views\Home\Index.cshtml"
               Write((ViewData["my_data"] as Data).Counter);

            
            #line default
            #line hidden
WriteLiteral("\r\n    My second counter is: ");

            
            #line 10 "..\..\Views\Home\Index.cshtml"
                     Write(ViewBag.Counter);

            
            #line default
            #line hidden
WriteLiteral("\r\n    User name is ");

            
            #line 11 "..\..\Views\Home\Index.cshtml"
            Write(ViewBag.UserName2);

            
            #line default
            #line hidden
WriteLiteral("\r\n    My third counter is :");

            
            #line 12 "..\..\Views\Home\Index.cshtml"
                     Write((TempData["my_data"] as Data).Counter);

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("Banner"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("Banner"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("Banner"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 25 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("Banner"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("Banner"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
